config/routes.rb
Skooter::Engine.routes.draw do


  resources :forms
  # Routes for submit and download forms viw ODK app
  resources :odk, defaults: { format: 'xml' }, only: [:index, :show]
  match '/submission', to: 'odk#submissions', via: :all, defaults: { format: 'xml' }

  # get '/formList', to: 'odk#index', defaults: { format: 'xml' }
  # get '/forms/:id', to: 'odk#show', defaults: { format: 'xml' }
  # match '/submission', to: 'odk#submissions', via: :all, defaults: { format: 'xml' }

end

app/models/skooter/application_record.rb
module Skooter
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/skooter/form.rb
module Skooter
  class Form < ApplicationRecord

    has_one_attached :document

  end
end

app/controllers/concerns/skooter/base_controller_actions.rb
module Skooter::BaseControllerActions
  extend ActiveSupport::Concern

  def index
    @forms = Skooter::Form.order(:name)
    respond_to do |format|
      format.xml { render 'index.xml' }
    end
  end

  def show
    doc = Skooter::Form.find(params[:id])
    if SKOOTER_CONFIG['PAPERCLIP_STORAGE'] == :s3 || :S3
      redirect_to doc.document.expiring_url(10.minutes.to_i)
    else
      send_file doc.document.path, type: doc.document_content_type, disposition: 'inline'
    end
  end

  def submissions
    if request.method == 'POST'
      hash = Crack::XML.parse(File.read(params[:xml_submission_file].path))
      model = set_model(hash)

      if model != 'device_id'
        object = prepare_object(model, hash)
        form = "Olpe::#{model.singularize.camelize}".constantize.new(object)
        respond_to do |format|
          if form.save
            format.xml { render status: 201 }
          else
            format.xml { render status: form.errors.messages }
          end
        end
      else
        render status: 201
      end
    else
      render status: 204
    end
  end
end

app/controllers/concerns/skooter/base_forms_controller_actions.rb
module Skooter
  ##
  module BaseFormsControllerActions
    extend ActiveSupport::Concern

    def self.included(base)
      base.helper_method :form, :forms
      base.respond_to :html
    end

    def create
      if form.save
        redirect_to form, notice: 'Form was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /forms/1
    def update
      if form.update(form_params)
        redirect_to form, notice: 'Form was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /forms/1
    def destroy
      form.destroy
      redirect_to forms_url, notice: 'Form was successfully destroyed.'
    end

    private

      def forms
        @forms ||= Form.all
      end

      def form
        @form ||= case action_name
                  when 'new'
                    Form.new
                  when 'create'
                    Form.new(form_params)
                  else
                    logger.debug "action rendered: #{action_name}"
                    Form.find(params[:id])
                  end
      end

      # Only allow a trusted parameter "white list" through.
      def form_params
        params.require(:form).permit(:name, :description, :document)
      end
  end
end

app/controllers/concerns/skooter/base_odk_controller_actions.rb
module Skooter
  ##
  module BaseOdkControllerActions
    extend ActiveSupport::Concern

    def self.included(base)
      base.before_action :set_header, only: %i[index submissions]
      base.respond_to :xml
    end

    def index
      @forms = Skooter::Form.order(:name)
      respond_to do |format|
        format.xml { render 'index.xml' }
      end
    end

    def show
      doc = Skooter::Form.find(params[:id])
      send_data doc.document.download, filename: doc.document.filename.to_s, content_type: doc.document.content_type
    end

    def submissions
      if request.method.eql?('POST')
        # put your logic code here like the below example
        # hash = Crack::XML.parse(File.read(params[:xml_submission_file].path))
        # model = set_model(hash)
        model = 'nothing_device'

        if model != 'device_id'
        #   object = prepare_object(model, hash)
        #   form = "Demo::#{model.singularize.camelize}".constantize.new(object)
        #   respond_to do |format|
        #     if form.save
        #       format.xml { render status: 201 }
        #     else
        #       format.xml { render status: form.errors.messages }
        #     end
        #   end
        else
          render status: 201
        end
      else
        render status: 204
      end
    end

    private

      def set_header
        response.headers['X-OpenRosa-Version'] = '1'
        response.headers['Content-Type'] = 'text/xml; charset=utf-8'
      end
  end
end

app/controllers/skooter/application_controller.rb
require_dependency 'skooter/application_controller'

module Skooter
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/skooter/forms_controller.rb
# frozen_string_literal: true

module Skooter
  ##
  class FormsController < ApplicationController
    include Skooter::BaseFormsControllerActions
    def destroy
      logger.debug "=========> action delete"
      form.destroy
      redirect_to forms_url, notice: 'Form was successfully destroyed.'
    end
  end
end

app/controllers/skooter/odk_controller.rb
# require_dependency 'skooter/application_controller'
module Skooter
  class OdkController < ApplicationController
    ## Resource for use ActiveSupport Concerns in order to make overwritable methods for ODK
    # Source
    # http://stackoverflow.com/questions/7719633/how-to-extend-rails-engines-controllers-properly
    # http://edgeguides.rubyonrails.org/engines.html#overriding-models-and-controllers
    ##
    ##
    ## Github Gist: https://gist.github.com/trejo08/11df06b3c6ff8fa26c610447005b721f
    include Skooter::BaseOdkControllerActions

    
  end
end

app/helpers/skooter/application_helper.rb
module Skooter
  module ApplicationHelper
  end
end

app/views/layouts/skooter/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skooter</title>
  <%#= stylesheet_link_tag    "skooter/application", media: "all" %>
  <%#= javascript_include_tag "skooter/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/skooter/forms/_form.html.erb
<%= form_for form do |f| %>
  
  <p>
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </p>


  <p>
    <%= f.label :description %>
    <%= f.text_field :description, required: true %>
  </p>

  <p>
    <%= f.label :document %>
    <%= f.file_field :document, required: true %>
  </p>
  
  <p>
    <%= f.submit "Submit" %>
  </p>

<% end %>

app/views/skooter/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: form %>

<%= link_to 'Show', form %> |
<%= link_to 'Back', forms_path %>

app/views/skooter/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>XML Form</th>
      <th colspan="3">actions</th>
    </tr>
  </thead>

  <tbody>
    <% forms.each do |xml_form| %>
      <tr>
        <td><%= xml_form.name %></td>
        <td>
          <% if xml_form.document.attached? %>
            <%= xml_form.document.filename %>
          <% else %>
            No File Attached
          <% end %>
        </td>
        <td><%= link_to 'Show', form_path(xml_form) %></td>
        <td><%= link_to 'Edit', edit_form_path(xml_form) %></td>
        <td>
          <%= link_to form_path(xml_form), data: { confirm: 'Are you sure?' }, method: :delete do %>
            destroy
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form', new_form_path %>

app/views/skooter/forms/new.html.erb
<h1>New Form</h1>
<%#= Rails.application.config.paperclip_defaults %>
<%#= render 'form', form: form %>
<%= render 'form', form: form %>

<%= link_to 'Back', forms_path %>

app/views/skooter/forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= form.name %>
</p>

<p>
  <strong>Uploaded file: </strong>
  
  <% if form.document.attached? %>
    <%= form.document.filename %>
  <% else %>
    No File Attached
  <% end %>

</p>
<%= link_to 'Edit', edit_form_path(form) %> |
<%= link_to 'Back', forms_path %>

app/views/skooter/odk/index.html.erb
<h1>Odk#index</h1>
<p>Find me in app/views/skooter/odk/index.html.erb</p>

app/views/skooter/odk/index.xml.erb
<?xml version='1.0' encoding='UTF-8' ?>
<xforms xmlns="http://openrosa.org/xforms/xformsList">
  <% @forms.each do |file| %>
  <xform>
    <formID><%= file.id %></formID>
    <name><%= file.name %></name>
    <version><%= file.updated_at.to_i %></version>
    <hash>md5:c28fc778a9291672badee04ac880a05d</hash>
    <descriptionText><%= file.description %></descriptionText>
    <!--<downloadUrl>https://progis.herokuapp.com/skooter/odk/<%#= file.id %></downloadUrl>-->
    <downloadUrl><%= ENV['DOMAIN'] %>/skooter/odk/<%= file.id %></downloadUrl>
  </xform>
  <% end %>
</xforms>

app/views/skooter/odk/show.html.erb
<h1>Odk#show</h1>
<p>Find me in app/views/skooter/odk/show.html.erb</p>

app/views/skooter/odk/submissions.html.erb
<h1>Odk#submissions</h1>
<p>Find me in app/views/skooter/odk/submissions.html.erb</p>